#!/bin/bash

trap 'kill 0' EXIT

if [[ ! $# = 1 || ! $1 = [1-9] ]] ; then echo "This script must be run with the group number as parameter." ; false ; exit ; fi ;

echo "Starting GUI with simu $1..."
cd ai4industry-gui-spring/
./gradlew bootRun &
cd ../ai4industry-gui-react/
npm install --legacy-peer-deps & 
pid=$!
wait $pid
echo "REACT_APP_SIMU=$1" > .env
npm start 

wait